server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: spring
    static_configs:
      - targets:
          - localhost
        labels:
          job: spring-logs
          __path__: /var/log/spring/*.log # Path where your apps write logs