global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080' # product-service
          - 'host.docker.internal:8081' # inventory-service
          - 'host.docker.internal:8082' # order-service
          - 'host.docker.internal:8083' # api-gateway
          - 'host.docker.internal:8084' # notification-service
          - 'host.docker.internal:8761' # eureka-server