services:
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - eureka

  grafana:
    image: grafana/grafana
    ports: ["3000:3000"]
    volumes:
      - ./grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    depends_on:
      - prometheus
      - loki
      - tempo

  loki:
    image: grafana/loki
    ports: ["3100:3100"]

  tempo:
    image: grafana/tempo
    ports: ["3200:3200"]
    command: ["-config.file=/etc/tempo.yaml"]

  eureka:
    build: ../eureka-server # Update this path to match your project structure
    ports: ["8761:8761"]
    environment:
      - SPRING_PROFILES_ACTIVE=prod