global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: 'http://eureka:8761/eureka'
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: application
      - source_labels: [__meta_eureka_instance_host]
        target_label: instance

  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8083']